# returns the semver which is higher of semver a  and b
   function(semver_higher a b)
    semver_gt("${a}" "${b}")
    ans(res)
    if(res)
      return(${a})
    else()
      return(${b})
    endif()
   endfunction()