## returns all identifiers for user data
function(user_data_ids)
  user_data_dir()
  ans(dir)
  glob("${dir}/*.cmake")
  ans(files)
  set(keys)
  foreach(file ${files})
    path_component("${file}" --file-name)
    ans(key)
    list(APPEND keys "${key}")
  endforeach()
  return_ref(keys)
endfunction()