function(obj_default_has_member obj key)
  map_has("${obj}" "${key}")
  ans(has_member)
  if(has_member)
    return(true)
  endif()
  obj_getprototype("${obj}")
  ans(proto)
  if(NOT proto)
    return(false)
  endif()
  obj_has("${proto}" "${key}")
  return_ans()
endfunction()