name: Test

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure macOS
      if: matrix.os == 'macos-latest'
      run: mkdir build && cd build && cmake -G Xcode ..
 
    - name: Configure Windows
      if: matrix.os == 'windows-latest'
      run: mkdir build && cd build && cmake ..

    - name: Build Debug
      run: cmake --build build --config Debug

    - name: Test Debug
      run: cd build && ctest -C Debug . -V --output-on-failure

    - name: Build Release
      run: cmake --build build --config Release

    - name: Test Release
      run: cd build && ctest -C Release . -V --output-on-failure
