macro(arguments_sequence __begin __end)
  arguments_encoded_list("${__begin}" "${__end}")
  ans(__list)
  sequence_new()
  ans(__result)
  foreach(__sublist ${__list})
    encoded_list_decode("${__sublist}")
    ans(__sublist)
    sequence_add("${__result}" "${__sublist}")
  endforeach()
  set(__ans "${__result}")
endmacro()
