function(markdown_include_sourcecode path)
  path("${path}")
  ans(qualified_path)
  if(EXISTS "${qualified_path}")  
    fread("${path}")
    ans(res)
    else()
      set(res "<file does not exist>")
    endif()
    set(res "*${path}*: \n```${ARGN}\n${res}\n```")
    return_ref(res)
endfunction()
