
## ensures that the directory specified exists 
## the directory is qualified with path()
function(dir_ensure_exists path)
  path("${path}")
  ans(path)
  if(EXISTS "${path}")
    if(IS_DIRECTORY "${path}")
      return("${path}")
    endif()
    return()
  endif()
  mkdir("${path}")
  return_ans()
endfunction()