

function(linked_list_pop_back linked_list)
  map_tryget(${linked_list} tail)
  ans(tail)
  if(NOT tail)
    return()
  endif()
  linked_list_remove("${linked_list}" "${tail}")
  if("${ARGN}_" STREQUAL "--node_")
    return("${tail}")
  endif()
  address_get("${tail}")
  return_ans()
endfunction()