
function(markdown_compile_function file)
  path_qualify(file)
  if(NOT "${file}" MATCHES "(.+)\\.cmake")
    message(FATAL_ERROR "invalid file")
  endif()
  set(target "${CMAKE_MATCH_1}.md")
  markdown_template_function_descriptions(${file})
  ans(res)
  if(NOT res)
    return()
  endif()
  fwrite("${target}" "${res}")
  return()
endfunction()