


  function(indexed_store_index_add)
    obj("${ARGN}")
    ans(index)
    if(NOT index)
      map_new()
      ans(index)
      map_set(${index} name "${ARGN}")
      set(selector "[]() ref_nav_get({{ARGN}} '${ARGN}')")
    else()
      map_tryget(${index} selector)
      ans(selector)
    endif()  
    callable("${selector}")
    ans(selector)
    map_set(${index} selector "${selector}")
    assign(this.indices[] = index)
    return_ref(index)
  endfunction()