
  function(indexed_store_find)
    indexed_store_find_keys("${ARGN}")
    ans(keys)
    set(result)
    foreach(key ${keys})
      assign(result[] = this.load("${key}"))
    endforeach()
    return_ref(result)
  endfunction()